on:
  push:
    paths:
      - .github/workflows/build-image-latest.yml
      - Dockerfile
      - entrypoint.sh
      - load_models.py
env:
  CONTAINER_REPOSITORY: ghcr.io/${{ github.repository }}
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - name: docker/pull
        run: |
          docker pull ${{ env.CONTAINER_REPOSITORY }}:latest
      - name: docker/build
        run: >
          docker build .
          -t ${{ env.CONTAINER_REPOSITORY }}:latest
      - name: docker/login
        run: >
          docker login ghcr.io
          --username ${{ github.repository_owner }}
          --password ${{ secrets.GITHUB_TOKEN }}
      - name: docker/push
        run: |
          docker push ${{ env.CONTAINER_REPOSITORY }}:latest
